force_refresh:
  target:
    entity:
      integration: ctek
  fields: {}
send_command:
  target:
    entity:
      integration: ctek
  fields:
    command:
      required: true
      example: REBOOT
      selector:
        text:
